name: Deploy

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build react project
        run: npm run build --if-present
        env:
          REACT_APP_API_KEY: ${{ secrets.DEVELOP_RPC_API }}
          REACT_APP_ASSET_MANTLE_API: ${{ secrets.DEVELOP_REST_API }}
          REACT_APP_FAUCET_SERVER: ${{ secrets.DEVELOP_APP_FAUCET }}
          REACT_APP_CHAIN_ID: ${{ secrets.DEVELOP_CHAIN_ID }}
          REACT_APP_CHAIN_NAME: ${{ secrets.DEVELOP_CHAIN_NAME }}
          CI: false
      - name: zip up the build
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r build.zip build
      - name: Operations
        uses: alinz/ssh-scp-action@master
        with:
          key: ${{ secrets.DEVELOP_SSH_KEY }}
          host: ${{ secrets.DEVELOP_HOST }}
          port: 22
          user: ${{ secrets.DEVELOP_USERNAME }}
          # runs this on remove server
          ssh_before: |
            rm -r build.zip
          # then uploads these 2 files
          scp: |
            build.zip ${{ secrets.DEVELOP_USERNAME }}@${{ secrets.DEVELOP_HOST }}:~/build.zip
          # then run these commands
          ssh_after: |
            ${{ secrets.DEVELOP_SCRIPT }}
